# -*- coding: utf-8 -*-
"""detecting_electrical_fault.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h523tNIT9yXaGNPOnG8j51aSpB-2mmMP

# Business Understanding

## Project Domain

## Problem Statements

## Goals

## Solution Statements

# Data Understanding

## Import data dari kaggle
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!ls ~/.kaggle

!kaggle datasets download -d esathyaprakash/electrical-fault-detection-and-classification

!mkdir electrical-fault-detection-and-classification
!unzip electrical-fault-detection-and-classification.zip -d detecting-electrical-faults
!ls detecting-electrical-faults

"""## Import Library yang dibutuhkan"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import scipy.stats as stats
from tensorflow import keras
from keras.models import Sequential
from tensorflow import keras
from keras.layers import Dense
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,BaggingClassifier,AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_score, recall_score
import warnings
warnings.filterwarnings('ignore')

"""## Exploratory Data Analysis"""

df = pd.read_csv('detecting-electrical-faults/detect_dataset.csv')

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

df.drop(['Unnamed: 7','Unnamed: 8'],axis=1,inplace = True)

df.duplicated().sum()

df['Output (S)'].unique()

fig,(ax1,ax2) = plt.subplots(1,2,figsize=(10,5))
ax1.bar(x=df['Output (S)'].unique(),height = df['Output (S)'].value_counts())
ax1.set_xticks(ticks=[0,1])

ax2.pie(df['Output (S)'].value_counts(),autopct='%0.2f',labels=df['Output (S)'].value_counts().index)

plt.suptitle('Frequency of both the classes')
plt.show()

plt.bar(x = df.columns , height = df.corr()['Output (S)'])
plt.axhline(y=0, color='black', linewidth=1)
plt.title('Correlation between Ouput(S) and other columns')
plt.show()

ls = ['Ia','Ib','Ic','Va','Vb','Vc']

plt.figure(figsize=(12, 5))
for i in range(2):
    for j in range(3):
        plt.subplot(2, 3, i * 3 + (j + 1))
        sns.kdeplot(df[ls[i * 3 + j]])

plt.subplots_adjust(hspace=0.5, wspace=0.5)
plt.suptitle('Kde distribution of all columns')
plt.show()

ls = ['Ia','Ib','Ic','Va','Vb','Vc']

plt.figure(figsize=(12, 5))
for i in range(2):
    for j in range(3):
        plt.subplot(2, 3, i * 3 + (j + 1))
        sns.boxplot(x=df[ls[i*3+j]])

plt.subplots_adjust(hspace=0.5, wspace=0.5)
plt.suptitle('Box plot of all columns')
plt.show()

ls = ['Ia','Ib','Ic','Va','Vb','Vc']

df_melted1 = df[ls[:3]].melt(var_name='Variable', value_name='Value')
df_melted2 = df[ls[3:]].melt(var_name='Variable', value_name='Value')

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

sns.stripplot(x='Variable', y='Value', data=df_melted1, ax=ax1)
ax1.set_title('Strip Plot of Ia, Ib, Ic')

sns.stripplot(x='Variable', y='Value', data=df_melted2, ax=ax2)
ax2.set_title('Strip Plot of Va, Vb, Vc')

fig.suptitle('Strip Plots of Different Sets of Variables', fontsize=16)

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

pair_plot = sns.pairplot(data=df.drop('Output (S)', axis=1))
pair_plot.fig.suptitle('Pair Plot of Features', fontsize=16)
pair_plot.fig.subplots_adjust(top=0.95)

plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(df.drop('Output (S)',axis=1).corr(), annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Heatmap')
plt.show()

ls = ['Ia', 'Ib', 'Ic', 'Va', 'Vb', 'Vc']

plt.figure(figsize=(12, 8))

for i in range(2):
    for j in range(3):
        plt.subplot(2, 3, i * 3 + (j + 1))
        stats.probplot(df[ls[i*3+j]], dist="norm", plot=plt)
        plt.title(ls[i*3+j])

plt.tight_layout()
plt.suptitle('QQ plots for all columns', y=1.05, fontsize=16)
plt.show()

"""# Data Preparation"""

df.head()

df.info()

print(df.columns)

x_train,x_test,y_train,y_test = train_test_split(df.drop('Output (S)',axis=1),df['Output (S)'],random_state=42,test_size=0.2)

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

"""# Modeling"""

model = Sequential()
model.add(Dense(256, activation='relu', input_shape = (x_train.shape[1],)))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

from tensorflow.keras.utils import plot_model
plot_model(model, show_shapes = True)

history = model.fit(x_train, y_train,
                    epochs=50,
                    batch_size=16,
                    validation_data=(x_test, y_test))

"""# Evaluation"""

# Evaluate the model
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

# Make predictions
y_pred = model.predict(x_test)
y_pred_classes = (y_pred > 0.5).astype(int)

# Print classification report
print(classification_report(y_test, y_pred_classes))

# Plot training history (optional)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

# Plot training history (optional)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

cm = confusion_matrix(y_test, y_pred_classes)
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

print("Classification Report:")
print(classification_report(y_test, y_pred_classes))

"""# Deployment

## Model Simulation
"""

df.head()

sample_index = np.random.randint(1, len(df))
sample_data = df.drop('Output (S)', axis=1).iloc[[sample_index]]

sample_data_scaled = sc.transform(sample_data)

prediction = model.predict(sample_data_scaled)
predicted = (prediction > 0.5).astype(int)

print(f"Sample data:\n{sample_data}")
print(f"\nPredicted: {predicted[0][0]}")
print(f"Actual : {df['Output (S)'].iloc[sample_index]}")

"""## Save Model"""

# Konversi model ke TFLite
import tensorflow as tf # Import TensorFlow before using it
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Simpan model
with open('detecting-electrical-faults.tflite', 'wb') as f:
    f.write(tflite_model)

# Simpan label encoder dan scaler
import joblib
# Since 'le' is not defined, create and fit it to your data if necessary.
# Assuming 'Output (S)' is the target column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['Output (S)'])
joblib.dump(le, 'label_encoder.pkl')
# If 'scaler' refers to the StandardScaler used earlier, change it to 'sc'
joblib.dump(sc, 'scaler.pkl')